name: CI Pipeline

on:
  push:
    branches:
      - main

permissions:
  issues: write

jobs:
  security_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Run OWASP ZAP
      #   id: zap_scan
      #   uses: zaproxy/action-baseline@v0.13.0
      #   with:
      #     docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
      #     target: 'https://preview.owasp-juice.shop'  
      #     cmd_options: '-a'
      
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1  # Use v1 to point to the latest stable version
        with:
          projectBaseDir: './'  
          args: >
            -Dsonar.organization=my-org
            -Dsonar.projectKey=juice-shop
            -Dsonar.sources=.

        env:
          SONAR_TOKEN: ${{ secrets.SONNAR_TOKEN }}  # Ensure the correct secret name for SonarCloud token
