#code for automatic redeploy automatic
#SI DÉCOMMENTER IL FAUT S'ASSURER DE COMMENTER LE CODE DE ZAP ET MODIFIER L'URL UNE FOIS REDEPLOYÉ


# name: Trigger auto deployment for tp2-8100

# # When this action will be executed
# on:
#   # Automatically trigger it when detected changes in repo
#   push:
#     branches: 
#       [ main ]
#     paths:
#     - '**'
#     - '.github/workflows/tp2-8100-AutoDeployTrigger-594e9009-010e-40e1-9520-d68a17a01823.yml'

#   # Allow manual trigger 
#   workflow_dispatch:      

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     permissions: 
#       id-token: write #This is required for requesting the OIDC JWT Token
#       contents: read #Required when GH token is used to authenticate with private repo

#     steps:
#       - name: Checkout to the branch
#         uses: actions/checkout@v2

#       - name: Azure Login
#         uses: azure/login@v1
#         with:
#           client-id: ${{ secrets.TP28100_AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.TP28100_AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.TP28100_AZURE_SUBSCRIPTION_ID }}

#       - name: Build and push container image to registry
#         uses: azure/container-apps-deploy-action@v2
#         with:
#           appSourcePath: ${{ github.workspace }}
#           _dockerfilePathKey_: _dockerfilePath_
#           registryUrl: docker.io
#           registryUsername: ${{ secrets.DOCKERHUB_USER }}
#           registryPassword: ${{ secrets.DOCKERHUB_LOGIN }}
#           containerAppName: tp2-8100
#           resourceGroup: EquipeRahamen
#           imageToBuild: ${{ secrets.DOCKERHUB_USER }}/tp2-8100:main
#           _buildArgumentsKey_: |
#             _buildArgumentsValues_


