name: CI Pipeline / Zap

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write
  security-events: write  # Allow CodeQL to upload results and create alerts

jobs:
  security_tests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the source code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Run OWASP ZAP scan
      - name: Run OWASP ZAP
        id: zap_scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://tp2-8100--uuagjmn.wittyisland-f2df98dd.eastus2.azurecontainerapps.io/login'  
          cmd_options: '-a -m 10'

    



 
